apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-production-app-backend
  name: app-backend
  namespace: production
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-production-app-backend
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-production-app-backend
    spec:
      containers:
        - image: registry.sec.devops.uniks.de/app-backend:0.1.6
          name: app-backend
          envFrom:
            - secretRef:
                name: mongo-secret
                optional: false
            - secretRef:
                name: keycloak-secret
                optional: false
      imagePullSecrets:
        - name: registry
